name: Selenium Async Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Start Docker Compose
        run: docker compose up -d --build

      - name: Docker ps
        run: docker ps

      # =========================
      # KAFKA READY CHECK
      # =========================
      - name: Wait Kafka
        run: |
          echo "Esperando Kafka..."
          for i in {1..60}; do
            docker exec qa-kafka-broker bash -c "echo > /dev/tcp/localhost/9092" && \
            echo "Kafka OK" && exit 0

            echo "Intento $i - Kafka no listo"
            sleep 2
          done
          docker logs qa-kafka-broker || true
          exit 1

      # =========================
      # BACKEND READY CHECK
      # =========================
      - name: Wait backend-server
        run: |
          echo "Esperando backend..."

          for i in {1..60}; do
            if curl -s http://localhost:8080/health | grep -q "UP"; then
              echo "Backend OK"
              exit 0
            fi

            echo "Intento $i - backend no listo"
            sleep 2
          done

          echo "Backend no respondió"
          docker logs qa-backend-server || true
          exit 1

      # =========================
      # FRONTEND READY CHECK
      # =========================
      - name: Wait frontend
        run: |
          echo "Esperando frontend..."

          for i in {1..60}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5173)

            if [ "$STATUS" = "200" ]; then
              echo "Frontend OK"
              exit 0
            fi

            echo "Intento $i - frontend no listo"
            sleep 2
          done

          docker logs qa-frontend || true
          exit 1

      # =========================
      # WORKER LOGS
      # =========================
      - name: Worker logs
        if: always()
        run: docker logs qa-backend-worker || true

      # =========================
      # SELENIUM TESTS
      # =========================
      - name: Run Selenium tests
        run: mvn clean test
        env:
          BASE_URL: http://localhost:5173
          BACKEND_URL: http://localhost:8080
          KAFKA_BROKER: kafka:29092

      # =========================
      # CLEANUP
      # =========================
      - name: Stop Docker
        if: always()
        run: docker compose down -v